name: UrbanHero
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_plugin_android_lifecycle: ^2.0.0
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any
  firebase_storage: any
  firebase_ui_database: any
  firebase_cloud_firestore: any
  firebase_database: any
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.9
  location: ^7.0.1
  pie_chart: ^5.4.0
  shared_preferences: ^2.3.2
  google_maps_flutter: any
  google_sign_in: any
  fluttertoast: any
  lottie: any
  connectivity_plus: ^6.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.0
  provider: ^6.1.2
  geocoding: any
  fl_chart: ^0.63.0
  flutter_map_heatmap: ^0.0.6






flutter1:
  uses-material-design: true
  assets:
    - assets/images/UrbanHero_icon.jpeg
    - assets/images/google.png
    - assets/
    - assets/images/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/UrbanHero_icon.jpeg"


  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

