// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxnkUlwEhYji9Lsj7EF_XR3b04dVCXTII',
    appId: '1:770884120013:web:003c62d48c17717a96e884',
    messagingSenderId: '770884120013',
    projectId: 'urbanhero-d2ae8',
    authDomain: 'urbanhero-d2ae8.firebaseapp.com',
    storageBucket: 'urbanhero-d2ae8.firebasestorage.app',
    measurementId: 'G-0BKDTH2J6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqV5f-zGaePgrUefyL8LIXi9pMnR_15NA',
    appId: '1:770884120013:android:a0393fb82fd674f696e884',
    messagingSenderId: '770884120013',
    projectId: 'urbanhero-d2ae8',
    storageBucket: 'urbanhero-d2ae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpRjc9QIC5UO_OOm5_LONiSb-lIg9xSbI',
    appId: '1:770884120013:ios:a0e096d2471379e596e884',
    messagingSenderId: '770884120013',
    projectId: 'urbanhero-d2ae8',
    storageBucket: 'urbanhero-d2ae8.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpRjc9QIC5UO_OOm5_LONiSb-lIg9xSbI',
    appId: '1:770884120013:ios:a0e096d2471379e596e884',
    messagingSenderId: '770884120013',
    projectId: 'urbanhero-d2ae8',
    storageBucket: 'urbanhero-d2ae8.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxnkUlwEhYji9Lsj7EF_XR3b04dVCXTII',
    appId: '1:770884120013:web:ac288a7f9ada6d1396e884',
    messagingSenderId: '770884120013',
    projectId: 'urbanhero-d2ae8',
    authDomain: 'urbanhero-d2ae8.firebaseapp.com',
    storageBucket: 'urbanhero-d2ae8.firebasestorage.app',
    measurementId: 'G-Y5P1FPECPB',
  );
}